plugins {
    id 'dev.hybridlabs.fabric'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation("dev.hybridlabs.hapi:hapi-common-1.20.1:1.1.0")
    modImplementation("dev.hybridlabs.hapi:hapi-fabric-1.20.1:1.1.0")

    modApi "software.bernie.geckolib:geckolib-fabric-$geckolib_version"
    include modImplementation("com.jamieswhiteshirt:reach-entity-attributes:$reach_entity_attributes_version")
    modApi("com.terraformersmc:modmenu:${modmenu_version}")
    modImplementation "maven.modrinth:lithostitched:${lithostitched_version}-fabric-1.20"
    modImplementation("com.terraformersmc:biolith-fabric:${biolith_version}") {
        exclude(group: "com.github.glitchfiend")
    }
    modRuntimeOnly "io.github.flemmli97:debugutils:$minecraft_version-$debug_utils_version-fabric"
    modImplementation "maven.modrinth:carpet:$carpet_version"
    modRuntimeOnly "maven.modrinth:cyanide:4.1.1-fabric"
    modImplementation "dev.emi:trinkets:${trinkets_version}"
}

fabricApi {
    configureDataGeneration {
        setModId("$mod_id")
        outputDirectory = file("src/generated/resources")
        client = true
    }
}

loom {
    mixin {
        useLegacyMixinAp = true
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
}

publishMods.platforms.configureEach {
    requires 'fabric-api', 'fabric-language-kotlin', 'trinkets', 'geckolib', 'biolith', 'lithostitched', 'hybrid-api'
}
