plugins {
    id 'dev.hybridlabs.fabric'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation("dev.hybridlabs.hapi:hapi-common-1.21.1:1.0.0")
    modImplementation("dev.hybridlabs.hapi:hapi-fabric-1.21.1:1.0.0")

    modApi "software.bernie.geckolib:geckolib-fabric-$geckolib_version"
    modApi("com.terraformersmc:modmenu:${modmenu_version}")
    modImplementation "maven.modrinth:lithostitched:${lithostitched_version}-fabric-1.21.1"
    modImplementation("com.terraformersmc:biolith-fabric:${biolith_version}") {
        exclude(group: "com.github.glitchfiend")
    }
    modImplementation "maven.modrinth:carpet:$carpet_version"

    modRuntimeOnly "io.github.flemmli97:debugutils:$minecraft_version-$debug_utils_version-fabric"
    //modRuntimeOnly "maven.modrinth:cyanide:5.0.0-fabric"
    modImplementation "dev.emi:trinkets:${trinkets_version}"
}

fabricApi {
    configureDataGeneration {
        setModId("$mod_id")
        outputDirectory = file("src/generated/resources")
    }
}

publishMods.platforms.configureEach {
    requires 'fabric-api', 'fabric-language-kotlin', 'trinkets', 'geckolib', 'biolith', 'lithostitched', 'hybrid-api'
}
