plugins {
    id 'fabric-loom' apply false
    id 'net.neoforged.moddev.legacyforge' apply false
    id 'org.jetbrains.changelog'
}

changelog {
    version = version
    path = file('CHANGELOG.md').canonicalPath
    groups = ['Added', 'Changed', 'Deprecated', 'Removed', 'Fixed', 'Security']
    lineSeparator = '\n'
}
