plugins {
    id 'fabric-loom' version '1.17-SNAPSHOT' apply(false)
    id 'net.neoforged.moddev' version '2.0.143' apply false
    id 'org.jetbrains.changelog' version '2.2.1'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

changelog {
    version = version
    path = file("CHANGELOG.md").canonicalPath
    groups = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]
    lineSeparator = "\n"
}
