# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.5.0
group=dev.hybridlabs
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Hybrid Aquatic
mod_author=Hybrid Labs
mod_id=hybrid-aquatic
forge_mod_id=hybrid_aquatic
license=ARR

credits=MysticKoko, Aqua, Andante, Eggo, Ragno, TheNuclearNexus, dragoncommands, murphy slaw

description=A mod that enhances your underwater Minecraft experience! Explore improved rivers, swamps, oceans, and undersea caves with new creatures, blocks, and (coming soon) biomes.

minecraft_version_range=[1.20.1, 1.22)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03
kotlin_version=2.1.20

# Fabric Deps
modmenu_version=7.2.2
reach_entity_attributes_version=2.4.0

# Dev only deps
debug_utils_version=1.0.5
carpet_version=1.4.112

# Common deps
geckolib_version=1.20.1:4.8.2
lithostitched_version=1.4.11
biolith_version=1.0.1-alpha.1

# Fabric
fabric_version=0.92.5+1.20.1
fabric_loader_version=0.16.13
fabric_kotlin_version=1.13.2

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false