pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Hybrid Labs'
            url = 'https://maven.dvitski.cc/releases'
        }
    }
}

plugins {
    // The shared build setup: https://github.com/hybridlabs/hybrid-gradle
    id 'dev.hybridlabs.multiloader' version '1.0.0'
}

// This should match the folder name of the project, or else IDEA may complain
// (see https://youtrack.jetbrains.com/issue/IDEA-317606)
rootProject.name = 'hybrid-aquatic'
include 'common'
include 'fabric'
include 'neoforge'
