plugins {
    id 'dev.hybridlabs.forge'
    id 'org.jetbrains.kotlin.jvm'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")
    config("${mod_id}.forge.mixins.json")
}

dependencies {
    modImplementation "software.bernie.geckolib:geckolib-forge-$geckolib_version"
    modImplementation "maven.modrinth:lithostitched:${lithostitched_version}-forge-1.20"
    modImplementation("com.terraformersmc:biolith-forge:${biolith_version}") {
        exclude(group: "com.github.glitchfiend")
    }

    modImplementation("dev.hybridlabs.hapi:hapi-forge-1.20.1:1.1.0")

    modCompileOnly "top.theillusivec4.curios:curios-forge:${curios_version}:api"
    modRuntimeOnly "top.theillusivec4.curios:curios-forge:${curios_version}"
}

publishMods.platforms.configureEach {
    requires 'kotlin-for-forge', 'curios', 'geckolib', 'biolith', 'lithostitched', 'hybrid-api'
}
