package dev.hybridlabs.aquatic.item

import dev.hybridlabs.aquatic.CommonClass
import dev.hybridlabs.aquatic.Constants
import dev.hybridlabs.aquatic.block.HABlocks
import dev.hybridlabs.aquatic.block.HAPlatformBlocks
import dev.hybridlabs.aquatic.block.MessageInABottleBlock
import dev.hybridlabs.aquatic.block.entity.MessageInABottleBlockEntity
import dev.hybridlabs.aquatic.platform.registration.RegistryObject
import dev.hybridlabs.hapi.item.HAPIItems
import net.minecraft.core.BlockPos
import net.minecraft.core.Holder
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.core.registries.Registries
import net.minecraft.network.chat.Component
import net.minecraft.world.entity.decoration.PaintingVariant
import net.minecraft.world.item.*
import net.minecraft.world.level.block.Blocks
import kotlin.jvm.optionals.getOrNull

object HAItemGroups {
    val BLOCKS = register(
        "blocks",
        CreativeModeTab.builder(CreativeModeTab.Row.TOP, 0)
            .title(Component.translatable("itemGroup.${Constants.MOD_ID}.blocks"))
            .icon { ItemStack(HAItems.ANEMONE.get()) }
            .displayItems { itemDisplayParameters, entries ->
                // blocks
                entries.accept(HABlocks.MESSAGE_IN_A_BOTTLE.get())
                entries.accept(HABlocks.SUSPICIOUS_RED_SAND.get())
                entries.accept(HABlocks.AERATED_SAND.get())
                entries.accept(HABlocks.BUBBLE_GEYSER.get())
                entries.accept(HABlocks.WHITE_SAND.get())
                entries.accept(HABlocks.WHITE_SANDSTONE.get())
                entries.accept(HABlocks.WHITE_SANDSTONE_STAIRS.get())
                entries.accept(HABlocks.WHITE_SANDSTONE_SLAB.get())
                entries.accept(HABlocks.WHITE_SANDSTONE_WALL.get())
                entries.accept(HABlocks.SMOOTH_WHITE_SANDSTONE.get())
                entries.accept(HABlocks.SMOOTH_WHITE_SANDSTONE_SLAB.get())
                entries.accept(HABlocks.SMOOTH_WHITE_SANDSTONE_STAIRS.get())
                entries.accept(HABlocks.CUT_WHITE_SANDSTONE.get())
                entries.accept(HABlocks.CUT_WHITE_SANDSTONE_SLAB.get())
                entries.accept(HABlocks.CHISELED_WHITE_SANDSTONE.get())
                entries.accept(HABlocks.GRASSY_SAND.get())
                entries.accept(HABlocks.CORALSTONE.get())
                entries.accept(HABlocks.SHORESTONE.get())
                entries.accept(HABlocks.BARNACLE_SHORESTONE.get())
                entries.accept(HABlocks.RED_BRINESTONE.get())
                entries.accept(HABlocks.RED_BRINESTONE_STAIRS.get())
                entries.accept(HABlocks.RED_BRINESTONE_SLAB.get())
                entries.accept(HABlocks.RED_BRINESTONE_WALL.get())
                entries.accept(HABlocks.RED_BRINESTONE_BRICKS.get())
                entries.accept(HABlocks.RED_BRINESTONE_BRICK_STAIRS.get())
                entries.accept(HABlocks.RED_BRINESTONE_BRICK_SLAB.get())
                entries.accept(HABlocks.RED_BRINESTONE_BRICK_WALL.get())
                entries.accept(HABlocks.CHISELED_RED_BRINESTONE.get())
                entries.accept(HABlocks.POLISHED_RED_BRINESTONE.get())
                entries.accept(HABlocks.POLISHED_RED_BRINESTONE_STAIRS.get())
                entries.accept(HABlocks.POLISHED_RED_BRINESTONE_SLAB.get())
                entries.accept(HABlocks.ORANGE_BRINESTONE.get())
                entries.accept(HABlocks.ORANGE_BRINESTONE_STAIRS.get())
                entries.accept(HABlocks.ORANGE_BRINESTONE_SLAB.get())
                entries.accept(HABlocks.ORANGE_BRINESTONE_WALL.get())
                entries.accept(HABlocks.ORANGE_BRINESTONE_BRICKS.get())
                entries.accept(HABlocks.ORANGE_BRINESTONE_BRICK_STAIRS.get())
                entries.accept(HABlocks.ORANGE_BRINESTONE_BRICK_SLAB.get())
                entries.accept(HABlocks.ORANGE_BRINESTONE_BRICK_WALL.get())
                entries.accept(HABlocks.CHISELED_ORANGE_BRINESTONE.get())
                entries.accept(HABlocks.POLISHED_ORANGE_BRINESTONE.get())
                entries.accept(HABlocks.POLISHED_ORANGE_BRINESTONE_STAIRS.get())
                entries.accept(HABlocks.POLISHED_ORANGE_BRINESTONE_SLAB.get())
                entries.accept(HABlocks.YELLOW_BRINESTONE.get())
                entries.accept(HABlocks.YELLOW_BRINESTONE_STAIRS.get())
                entries.accept(HABlocks.YELLOW_BRINESTONE_SLAB.get())
                entries.accept(HABlocks.YELLOW_BRINESTONE_WALL.get())
                entries.accept(HABlocks.YELLOW_BRINESTONE_BRICKS.get())
                entries.accept(HABlocks.YELLOW_BRINESTONE_BRICK_STAIRS.get())
                entries.accept(HABlocks.YELLOW_BRINESTONE_BRICK_SLAB.get())
                entries.accept(HABlocks.YELLOW_BRINESTONE_BRICK_WALL.get())
                entries.accept(HABlocks.CHISELED_YELLOW_BRINESTONE.get())
                entries.accept(HABlocks.POLISHED_YELLOW_BRINESTONE.get())
                entries.accept(HABlocks.POLISHED_YELLOW_BRINESTONE_STAIRS.get())
                entries.accept(HABlocks.POLISHED_YELLOW_BRINESTONE_SLAB.get())
                entries.accept(HABlocks.SCHIST.get())
                entries.accept(HABlocks.SCHIST_STAIRS.get())
                entries.accept(HABlocks.SCHIST_SLAB.get())
                entries.accept(HABlocks.SCHIST_WALL.get())
                entries.accept(HABlocks.SCHIST_BRICKS.get())
                entries.accept(HABlocks.SCHIST_BRICK_STAIRS.get())
                entries.accept(HABlocks.SCHIST_BRICK_SLAB.get())
                entries.accept(HABlocks.SCHIST_BRICK_WALL.get())
                entries.accept(HABlocks.CHISELED_SCHIST.get())
                entries.accept(HABlocks.POLISHED_SCHIST.get())
                entries.accept(HABlocks.POLISHED_SCHIST_STAIRS.get())
                entries.accept(HABlocks.POLISHED_SCHIST_SLAB.get())
                entries.accept(HABlocks.CHIMNEYSTONE.get())
                entries.accept(HABlocks.CHIMNEYSTONE_STAIRS.get())
                entries.accept(HABlocks.CHIMNEYSTONE_SLAB.get())
                entries.accept(HABlocks.CHIMNEYSTONE_WALL.get())
                entries.accept(HABlocks.CHIMNEYSTONE_BRICKS.get())
                entries.accept(HABlocks.CHIMNEYSTONE_BRICK_STAIRS.get())
                entries.accept(HABlocks.CHIMNEYSTONE_BRICK_SLAB.get())
                entries.accept(HABlocks.CHIMNEYSTONE_BRICK_WALL.get())
                entries.accept(HABlocks.CHISELED_CHIMNEYSTONE.get())
                entries.accept(HABlocks.POLISHED_CHIMNEYSTONE.get())
                entries.accept(HABlocks.POLISHED_CHIMNEYSTONE_STAIRS.get())
                entries.accept(HABlocks.POLISHED_CHIMNEYSTONE_SLAB.get())
                entries.accept(HAItems.GIANT_THERMAL_VENT.get())
                entries.accept(HAItems.HYDROTHERMAL_VENT.get())
                entries.accept(HAItems.CRYSTALLINE_SULFUR.get())
                entries.accept(HABlocks.MARINE_SNOW.get())
                entries.accept(Blocks.BONE_BLOCK)
                entries.accept(HABlocks.BONE_STAIRS.get())
                entries.accept(HABlocks.BONE_SLAB.get())
                entries.accept(HABlocks.BONE_WALL.get())
                entries.accept(HABlocks.BONE_FENCE.get())

                entries.accept(HAPlatformBlocks.DRIFTWOOD_LOG.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_WOOD.get())
                entries.accept(HAPlatformBlocks.STRIPPED_DRIFTWOOD_LOG.get())
                entries.accept(HAPlatformBlocks.STRIPPED_DRIFTWOOD_WOOD.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_PLANKS.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_STAIRS.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_SLAB.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_FENCE.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_FENCE_GATE.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_DOOR.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_TRAPDOOR.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_PRESSURE_PLATE.get())
                entries.accept(HAPlatformBlocks.DRIFTWOOD_BUTTON.get())

                entries.accept(HABlocks.CRAB_POT.get())
                entries.accept(HABlocks.HYBRID_CRATE.get())
                entries.accept(HABlocks.OAK_CRATE.get())
                entries.accept(HABlocks.SPRUCE_CRATE.get())
                entries.accept(HABlocks.BIRCH_CRATE.get())
                entries.accept(HABlocks.DARK_OAK_CRATE.get())
                entries.accept(HABlocks.JUNGLE_CRATE.get())
                entries.accept(HABlocks.BAMBOO_CRATE.get())
                entries.accept(HABlocks.ACACIA_CRATE.get())
                entries.accept(HABlocks.MANGROVE_CRATE.get())
                entries.accept(HABlocks.CHERRY_CRATE.get())
                entries.accept(HABlocks.PEARL_BLOCK.get())
                entries.accept(HABlocks.BLACK_PEARL_BLOCK.get())
                entries.accept(HAPlatformBlocks.HAGSLIME_BLOCK.get())
                entries.accept(HAPlatformBlocks.GLOWSLIME_BLOCK.get())
                entries.accept(HABlocks.GLOWSTICK.get())
                entries.accept(HAItems.BUOY.get())
                entries.accept(HAItems.BELL_BUOY.get())
                entries.accept(HAItems.RAFT.get())
                entries.accept(HAItems.OAK_RAFT.get())
                entries.accept(HAItems.SPRUCE_RAFT.get())
                entries.accept(HAItems.BIRCH_RAFT.get())
                entries.accept(HAItems.DARK_OAK_RAFT.get())
                entries.accept(HAItems.JUNGLE_RAFT.get())
                entries.accept(HAItems.ACACIA_RAFT.get())
                entries.accept(HAItems.MANGROVE_RAFT.get())
                entries.accept(HAItems.CHERRY_RAFT.get())
                entries.accept(HAItems.DRIFTWOOD_RAFT.get())

                entries.accept(HAPlatformItems.DUNEGRASS.get())
                entries.accept(HAPlatformItems.TALL_DUNEGRASS.get())
                entries.accept(HAItems.SEA_LETTUCE.get())
                entries.accept(HAItems.SHORT_RED_ALGAE.get())
                entries.accept(HAItems.RED_ALGAE.get())
                entries.accept(HAItems.DELESSERIA.get())
                entries.accept(HAItems.BULL_KELP.get())
                entries.accept(HAItems.SARGASSUM.get())
                entries.accept(HAItems.FLOATING_SARGASSUM.get())
                entries.accept(HAItems.WATER_LETTUCE.get())
                entries.accept(HAItems.WATER_HYACINTH.get())
                entries.accept(HAItems.JUNGLE_LILY_PAD.get())

                entries.accept(HAItems.SUN_CORAL_BLOCK.get())
                entries.accept(HAItems.LEAF_CORAL_BLOCK.get())
                entries.accept(HAItems.BUTTON_CORAL_BLOCK.get())
                entries.accept(HAItems.ROSE_CORAL_BLOCK.get())
                entries.accept(HAItems.BAMBOO_CORAL_BLOCK.get())
                entries.accept(HAItems.ZIGZAG_CORAL_BLOCK.get())
                entries.accept(HAItems.LOPHELIA_CORAL_BLOCK.get())
                entries.accept(HAItems.THORN_CORAL_BLOCK.get())

                entries.accept(HAItems.DEAD_SUN_CORAL_BLOCK.get())
                entries.accept(HAItems.DEAD_LEAF_CORAL_BLOCK.get())
                entries.accept(HAItems.DEAD_BUTTON_CORAL_BLOCK.get())
                entries.accept(HAItems.DEAD_ROSE_CORAL_BLOCK.get())
                entries.accept(HAItems.DEAD_BAMBOO_CORAL_BLOCK.get())
                entries.accept(HAItems.DEAD_ZIGZAG_CORAL_BLOCK.get())
                entries.accept(HAItems.DEAD_LOPHELIA_CORAL_BLOCK.get())
                entries.accept(HAItems.DEAD_THORN_CORAL_BLOCK.get())

                entries.accept(HAItems.BLEACHED_SUN_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_LEAF_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_BUTTON_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_ROSE_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_BAMBOO_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_ZIGZAG_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_LOPHELIA_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_THORN_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_FIRE_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_TUBE_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_HORN_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_BRAIN_CORAL_BLOCK.get())
                entries.accept(HAItems.BLEACHED_BUBBLE_CORAL_BLOCK.get())

                entries.accept(HAItems.SUN_CORAL.get())
                entries.accept(HAItems.LEAF_CORAL.get())
                entries.accept(HAItems.BUTTON_CORAL.get())
                entries.accept(HAItems.ROSE_CORAL.get())
                entries.accept(HAItems.BAMBOO_CORAL.get())
                entries.accept(HAItems.ZIGZAG_CORAL.get())
                entries.accept(HAItems.LOPHELIA_CORAL.get())
                entries.accept(HAItems.THORN_CORAL.get())

                entries.accept(HAItems.DEAD_SUN_CORAL.get())
                entries.accept(HAItems.DEAD_LEAF_CORAL.get())
                entries.accept(HAItems.DEAD_BUTTON_CORAL.get())
                entries.accept(HAItems.DEAD_ROSE_CORAL.get())
                entries.accept(HAItems.DEAD_BAMBOO_CORAL.get())
                entries.accept(HAItems.DEAD_ZIGZAG_CORAL.get())
                entries.accept(HAItems.DEAD_LOPHELIA_CORAL.get())
                entries.accept(HAItems.DEAD_THORN_CORAL.get())

                entries.accept(HAItems.BLEACHED_SUN_CORAL.get())
                entries.accept(HAItems.BLEACHED_LEAF_CORAL.get())
                entries.accept(HAItems.BLEACHED_BUTTON_CORAL.get())
                entries.accept(HAItems.BLEACHED_ROSE_CORAL.get())
                entries.accept(HAItems.BLEACHED_BAMBOO_CORAL.get())
                entries.accept(HAItems.BLEACHED_ZIGZAG_CORAL.get())
                entries.accept(HAItems.BLEACHED_LOPHELIA_CORAL.get())
                entries.accept(HAItems.BLEACHED_THORN_CORAL.get())
                entries.accept(HAItems.BLEACHED_FIRE_CORAL.get())
                entries.accept(HAItems.BLEACHED_TUBE_CORAL.get())
                entries.accept(HAItems.BLEACHED_HORN_CORAL.get())
                entries.accept(HAItems.BLEACHED_BRAIN_CORAL.get())
                entries.accept(HAItems.BLEACHED_BUBBLE_CORAL.get())

                entries.accept(HAItems.SUN_CORAL_FAN.get())
                entries.accept(HAItems.LEAF_CORAL_FAN.get())
                entries.accept(HAItems.BUTTON_CORAL_FAN.get())
                entries.accept(HAItems.ROSE_CORAL_FAN.get())
                entries.accept(HAItems.BAMBOO_CORAL_FAN.get())
                entries.accept(HAItems.ZIGZAG_CORAL_FAN.get())
                entries.accept(HAItems.LOPHELIA_CORAL_FAN.get())
                entries.accept(HAItems.THORN_CORAL_FAN.get())

                entries.accept(HAItems.DEAD_SUN_CORAL_FAN.get())
                entries.accept(HAItems.DEAD_LEAF_CORAL_FAN.get())
                entries.accept(HAItems.DEAD_BUTTON_CORAL_FAN.get())
                entries.accept(HAItems.DEAD_ROSE_CORAL_FAN.get())
                entries.accept(HAItems.DEAD_BAMBOO_CORAL_FAN.get())
                entries.accept(HAItems.DEAD_ZIGZAG_CORAL_FAN.get())
                entries.accept(HAItems.DEAD_LOPHELIA_CORAL_FAN.get())
                entries.accept(HAItems.DEAD_THORN_CORAL_FAN.get())

                entries.accept(HAItems.BLEACHED_SUN_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_LEAF_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_BUTTON_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_ROSE_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_BAMBOO_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_ZIGZAG_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_LOPHELIA_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_THORN_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_FIRE_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_TUBE_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_HORN_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_BRAIN_CORAL_FAN.get())
                entries.accept(HAItems.BLEACHED_BUBBLE_CORAL_FAN.get())

                entries.accept(HABlocks.ANEMONE.get())
                entries.accept(HABlocks.GIANT_GREEN_ANEMONE.get())
                entries.accept(HABlocks.STRAWBERRY_ANEMONE.get())
                entries.accept(HAItems.GIANT_CLAM.get())
                entries.accept(HAItems.OYSTER_BLOCK.get())
                entries.accept(HAItems.TUBE_SPONGE.get())
                entries.accept(HAItems.GLASS_SPONGE.get())
                entries.accept(HAItems.HARP_SPONGE.get())
                entries.accept(HAItems.PING_PONG_SPONGE.get())
                entries.accept(HAItems.BONE_WORMS.get())
                entries.accept(HAItems.TUBE_WORM.get())
                entries.accept(HAItems.DEPTH_CHARGE.get())
                entries.accept(HABlocks.BASKING_SHARK_PLUSHIE.get())
                entries.accept(HABlocks.BULL_SHARK_PLUSHIE.get())
                entries.accept(HABlocks.FRILLED_SHARK_PLUSHIE.get())
                entries.accept(HABlocks.GREAT_WHITE_SHARK_PLUSHIE.get())
                entries.accept(HABlocks.HAMMERHEAD_SHARK_PLUSHIE.get())
                entries.accept(HABlocks.THRESHER_SHARK_PLUSHIE.get())
                entries.accept(HABlocks.TIGER_SHARK_PLUSHIE.get())
                entries.accept(HABlocks.WHALE_SHARK_PLUSHIE.get())

                BuiltInRegistries.ITEM.forEach { item ->
                    val id = BuiltInRegistries.ITEM.getKey(item)
                    if (id.namespace != Constants.MOD_ID) {
                        return@forEach
                    }
                }

                itemDisplayParameters.holders().lookup(Registries.PAINTING_VARIANT).ifPresent { registryLookup ->
                    CreativeModeTabs.generatePresetPaintings(
                        entries,
                        itemDisplayParameters.holders(),
                        registryLookup,
                        { holder: Holder<PaintingVariant> -> holder.unwrapKey().getOrNull()?.location()?.namespace == Constants.MOD_ID },
                        CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS
                    )
                }
            }
            .build()
    )

    val ITEMS = register(
        "items",
        CreativeModeTab.builder(CreativeModeTab.Row.TOP, 0)
            .title(Component.translatable("itemGroup.${Constants.MOD_ID}.items"))
            .icon { ItemStack(HAItems.BARBED_HOOK.get()) }
            .displayItems { _, entries ->

                // food items
                entries.accept(HAItems.RAW_FISH_MEAT.get())
                entries.accept(HAItems.COOKED_FISH_MEAT.get())
                entries.accept(HAItems.RAW_FISH_STEAK.get())
                entries.accept(HAItems.COOKED_FISH_STEAK.get())
                entries.accept(HAItems.SIRENIAN_BEEF.get())
                entries.accept(HAItems.SIRENIAN_STEAK.get())
                entries.accept(HAItems.RAW_TENTACLE.get())
                entries.accept(HAItems.COOKED_TENTACLE.get())
                entries.accept(HAItems.RAW_SHRIMP.get())
                entries.accept(HAItems.COOKED_SHRIMP.get())
                entries.accept(HAItems.RAW_CRAYFISH.get())
                entries.accept(HAItems.COOKED_CRAYFISH.get())
                entries.accept(HAItems.RAW_CRAB.get())
                entries.accept(HAItems.COOKED_CRAB.get())
                entries.accept(HAItems.RAW_LOBSTER.get())
                entries.accept(HAItems.COOKED_LOBSTER.get())
                entries.accept(HAItems.RAW_LOBSTER_TAIL.get())
                entries.accept(HAItems.COOKED_LOBSTER_TAIL.get())
                entries.accept(HAItems.UNI.get())
                entries.accept(HAItems.CLAM.get())
                entries.accept(HAItems.COOKED_CLAM.get())
                entries.accept(HAItems.MUSSEL.get())
                entries.accept(HAItems.COOKED_MUSSEL.get())

                entries.accept(HAItems.AFRICAN_BUTTERFLYFISH.get())
                entries.accept(HAItems.BETTA.get())
                entries.accept(HAItems.DANIO.get())
                entries.accept(HAItems.TETRA.get())
                entries.accept(HAItems.DISCUS.get())
                entries.accept(HAItems.TIGER_BARB.get())
                entries.accept(HAItems.CICHLID.get())
                entries.accept(HAItems.GOURAMI.get())
                entries.accept(HAItems.PIRANHA.get())
                entries.accept(HAItems.CARP.get())
                entries.accept(HAItems.GOLDFISH.get())
                entries.accept(HAItems.TROUT.get())
                entries.accept(HAItems.SUNFISH.get())
                entries.accept(HAItems.PLECO.get())
                entries.accept(HAItems.ANGLERFISH.get())
                entries.accept(HAItems.BARRELEYE.get())
                entries.accept(HAItems.DRAGONFISH.get())
                entries.accept(HAItems.BLOBFISH.get())
                entries.accept(HAItems.HAGFISH.get())
                entries.accept(HAItems.FLASHLIGHT_FISH.get())
                entries.accept(HAItems.RATFISH.get())
                entries.accept(HAItems.SQUIRRELFISH.get())
                entries.accept(HAItems.CLOWNFISH.get())
                entries.accept(HAItems.SURGEONFISH.get())
                entries.accept(HAItems.DAMSELFISH.get())
                entries.accept(HAItems.SEAHORSE.get())
                entries.accept(HAItems.MACKEREL.get())
                entries.accept(HAItems.HERRING.get())
                entries.accept(HAItems.FLYING_FISH.get())
                entries.accept(HAItems.JOHN_DORY.get())
                entries.accept(HAItems.PEARLFISH.get())
                entries.accept(HAItems.SNAILFISH.get())
                entries.accept(HAItems.BOXFISH.get())
                entries.accept(HAItems.BLOWFISH.get())
                entries.accept(HAItems.STONEFISH.get())
                entries.accept(HAItems.GOLDEN_DORADO.get())
                entries.accept(HAItems.LIONFISH.get())
                entries.accept(HAItems.STINGRAY.get())
                entries.accept(HAItems.TRIGGERFISH.get())
                entries.accept(HAItems.TREVALLY.get())
                entries.accept(HAItems.ROCKFISH.get())
                entries.accept(HAItems.SEA_BASS.get())
                entries.accept(HAItems.COELACANTH.get())
                entries.accept(HAItems.NEEDLEFISH.get())
                entries.accept(HAItems.PARROTFISH.get())
                entries.accept(HAItems.SHEEPSHEAD_WRASSE.get())
                entries.accept(HAItems.MORAY_EEL.get())
                entries.accept(HAItems.TUNA.get())
                entries.accept(HAItems.MAHI.get())
                entries.accept(HAItems.OPAH.get())
                entries.accept(HAItems.OARFISH.get())
                entries.accept(HAItems.OCEAN_SUNFISH.get())

                // miscellaneous items
                entries.accept(HAItems.LOBSTER_CLAW.get())
                entries.accept(HAItems.COCONUT_CRAB_CLAW.get())
                entries.accept(HAItems.DUNGENESS_CRAB_CLAW.get())
                entries.accept(HAItems.FIDDLER_CRAB_CLAW.get())
                entries.accept(HAItems.VAMPIRE_CRAB_CLAW.get())
                entries.accept(HAItems.FLOWER_CRAB_CLAW.get())
                entries.accept(HAItems.GHOST_CRAB_CLAW.get())
                entries.accept(HAItems.LIGHTFOOT_CRAB_CLAW.get())
                entries.accept(HAItems.YETI_CRAB_CLAW.get())
                entries.accept(HAItems.SPIDER_CRAB_CLAW.get())
                entries.accept(HAItems.KARKINOS_CLAW.get())
                entries.accept(HAItems.HAGSLIME.get())
                entries.accept(HAItems.GLOWSLIME.get())
                entries.accept(HAItems.SHARK_TOOTH.get())
                entries.accept(HAItems.STARFISH.get())
                entries.accept(HAItems.PEARL.get())
                entries.accept(HAItems.BLACK_PEARL.get())
                entries.accept(HAItems.COMICALLY_LARGE_NAUTILUS_SHELL.get())
                entries.accept(HAItems.ARGONAUT.get())
                entries.accept(HAItems.SULFUR.get())
                entries.accept(HAItems.TUBE_SPONGE.get())
                entries.accept(HAItems.BUOY.get())
                entries.accept(HAItems.BELL_BUOY.get())
                entries.accept(HAItems.CUTTLEBONE.get())
                entries.accept(HAItems.FISH_FOOD.get())
                entries.accept(HAItems.CORAL_CHUNK.get())
                entries.accept(HAItems.PRISMARINE_ROD.get())
                entries.accept(HAItems.SEA_URCHIN_SPINE.get())

                // lures
                entries.accept(HAItems.BARBED_HOOK.get())
                entries.accept(HAItems.GLOWING_HOOK.get())
                entries.accept(HAItems.MAGNETIC_HOOK.get())
                entries.accept(HAItems.CREEPERMAGNET_HOOK.get())
                entries.accept(HAItems.OMINOUS_HOOK.get())
                entries.accept(HAItems.OMINOUS_CONCH.get())

                // tools
                entries.accept(HAPlatformItems.BRINE_BUCKET.get())
                entries.accept(HAItems.DIVING_WEIGHT.get())
                entries.accept(HAItems.SEASHELL_SPEAR.get())
                entries.accept(HAItems.SEASHELL_PICKAXE.get())
                entries.accept(HAItems.SEASHELL_AXE.get())
                entries.accept(HAItems.SEASHELL_SHOVEL.get())
                entries.accept(HAItems.SEASHELL_HOE.get())
                entries.accept(HAItems.CORAL_BLADE.get())
                entries.accept(HAItems.CORAL_PICKAXE.get())
                entries.accept(HAItems.CORAL_AXE.get())
                entries.accept(HAItems.CORAL_SHOVEL.get())
                entries.accept(HAItems.CORAL_HOE.get())
                entries.accept(HAPIItems.CREATURE_NET.get())
                entries.accept(HAItems.DIVING_ARMOR_UPGRADE_TEMPLATE.get())

                entries.accept(HAItems.DIVING_HELMET.get())
                entries.accept(HAItems.DIVING_SUIT.get())
                entries.accept(HAItems.DIVING_LEGGINGS.get())
                entries.accept(HAItems.DIVING_BOOTS.get())
                entries.accept(HAItems.REINFORCED_DIVING_HELMET.get())
                entries.accept(HAItems.REINFORCED_DIVING_SUIT.get())
                entries.accept(HAItems.REINFORCED_DIVING_LEGGINGS.get())
                entries.accept(HAItems.REINFORCED_DIVING_BOOTS.get())
                entries.accept(HAItems.GLOWING_DIVING_HELMET.get())
                entries.accept(HAItems.GLOWING_DIVING_SUIT.get())
                entries.accept(HAItems.GLOWING_DIVING_LEGGINGS.get())
                entries.accept(HAItems.GLOWING_DIVING_BOOTS.get())
                entries.accept(HAItems.NAUTILUS_HELMET.get())
                entries.accept(HAItems.NAUTILUS_PAULDRONS.get())
                entries.accept(Items.TURTLE_HELMET)
                entries.accept(HAItems.TURTLE_CHESTPLATE.get())
                entries.accept(HAItems.MANGLERFISH_LURE.get())
                entries.accept(HAItems.MANGLERFISH_FIN.get())
                entries.accept(HAItems.EEL_SCARF.get())
                entries.accept(HAItems.STRIPED_EEL_SCARF.get())
                entries.accept(HAItems.PINK_HATXOLOTL.get())
                entries.accept(HAItems.CYAN_HATXOLOTL.get())
                entries.accept(HAItems.BLUE_HATXOLOTL.get())
                entries.accept(HAItems.BROWN_HATXOLOTL.get())
                entries.accept(HAItems.GOLD_HATXOLOTL.get())
                entries.accept(HAItems.MOON_JELLYFISH_HAT.get())


                // spawn eggs
                BuiltInRegistries.ITEM.forEach { item ->
                    val id = BuiltInRegistries.ITEM.getKey(item)
                    if (id.namespace != Constants.MOD_ID) {
                        return@forEach
                    }
                }
            }
            .build()
    )

    val SPAWN_EGGS = register(
        "spawn_eggs",

        CreativeModeTab.builder(CreativeModeTab.Row.TOP, 0)
            .title(Component.translatable("itemGroup.${Constants.MOD_ID}.spawn_eggs"))
            .icon { ItemStack(HAItems.TUNA.get()) }
            .displayItems { _, entries ->
                BuiltInRegistries.ITEM.forEach { item ->
                    val id = BuiltInRegistries.ITEM.getKey(item)
                    if (id.namespace != Constants.MOD_ID) {
                        return@forEach
                    }
                    if (item is SpawnEggItem) {

                        entries.accept(item)
                    }
                }
            }
            .build()
    )

    private fun register(id: String, itemGroup: CreativeModeTab): RegistryObject<CreativeModeTab> {
        return CommonClass.CREATIVE_MODE_TABS.register(id) { itemGroup }
    }
}
