plugins {
    id 'dev.hybridlabs.common'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation 'com.google.code.findbugs:jsr305:3.0.1'

    implementation("dev.hybridlabs.hapi:hapi-common-1.21.1:1.0.0")

    implementation "software.bernie.geckolib:geckolib-neoforge-${geckolib_version}"

    implementation("com.terraformersmc:biolith-forge:${biolith_version}") {
        exclude(group: "com.github.glitchfiend")
    }
}
