plugins {
    id 'dev.hybridlabs.common'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation("dev.hybridlabs.hapi:hapi-common-1.20.1:1.1.0")

    modImplementation "software.bernie.geckolib:geckolib-forge-$geckolib_version"

    implementation("com.terraformersmc:biolith-forge:${biolith_version}") {
        exclude(group: "com.github.glitchfiend")
    }
    modImplementation "maven.modrinth:lithostitched:${lithostitched_version}-forge-1.20"
}
