plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
    id 'org.jetbrains.kotlin.jvm'
}

legacyForge {
    validateAccessTransformers = false
    mcpVersion = minecraft_version
    accessTransformers = [project(':common').file("src/main/resources/META-INF/accesstransformer.cfg")]
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/releases/"
    }

    maven {
        name = "Jitpack"
        url = "https://jitpack.io/"
    }

    maven {
        name = "Geckolib"
        url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
    }

    maven {
        name = "JamiesWhiteShirt"
        url = "https://maven.jamieswhiteshirt.com/libs-release/"
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven/"
    }

    maven {
        name = "Debug Utils (GitLab)"
        url = "https://gitlab.com/api/v4/projects/21830712/packages/maven/"
    }

    maven {
        name = "Minecraft Forge"
        url = "https://maven.minecraftforge.net/"
    }
    mavenCentral()
}


dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0"))
    implementation 'org.jetbrains:annotations:25.0.0'

    //We load the Forge version of any included mod dependencies
    modImplementation "software.bernie.geckolib:geckolib-forge-$geckolib_version"

    implementation("com.terraformersmc:biolith-forge:${biolith_version}") {
        exclude(group: "com.github.glitchfiend")
    }
    modImplementation "maven.modrinth:lithostitched:${lithostitched_version}-forge-1.20"

}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }

    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'kotlin'


    repositories {
        mavenCentral()
    }

    compileKotlin {
        if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
            accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
        }
        source(project(":common").sourceSets.main.allSource)
        inputs.file "../gradle.properties"
    }
}
