modLoader = "kotlinforforge"

loaderVersion = "[4,)"
license = "${license}"
issueTrackerURL="https://github.com/hybridlabs/hybrid-aquatic/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://hybridlabs.net/"
logoFile = "${mod_id}.png"
credits = '''${credits}'''
authors = "${mod_author}"
description = '''${description}'''
enumExtensions="META-INF/enumextensions.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "[4.8.3,)"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "biolith"
type = "required"
versionRange = "[1.0.1-alpha.1,)"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "required"
versionRange = "[5.9.1+1.20.1,)"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "lithostitched"
type = "required"
versionRange = "[1.4.11,)"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "hapi"
type = "required"
versionRange = "[1.0.0,)"
side = "BOTH"

[[mixins]]
config = "${mod_id}.forge.mixins.json"
