plugins {
    id 'dev.hybridlabs.neoforge'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation "software.bernie.geckolib:geckolib-neoforge-$geckolib_version"
    // Bundled unmodified under LGPL-3.0; see https://github.com/TerraformersMC/Biolith
    jarJar implementation("com.terraformersmc:biolith-neoforge:${biolith_version}") {
        exclude(group: "com.github.glitchfiend")
    }
    implementation("dev.hybridlabs.hapi:hapi-neoforge-1.21.1:1.1.2")

    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
}

publishMods.platforms.configureEach {
    requires 'kotlin-for-forge', 'geckolib', 'hybrid-api'
    embeds 'biolith'
    optional 'curios'
}
