plugins {
    id 'dev.hybridlabs.neoforge'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation "software.bernie.geckolib:geckolib-neoforge-$geckolib_version"
    implementation "maven.modrinth:lithostitched:${lithostitched_version}-neoforge-1.21.1"
    implementation("com.terraformersmc:biolith-neoforge:${biolith_version}") {
        exclude(group: "com.github.glitchfiend")
    }
    implementation("dev.hybridlabs.hapi:hapi-neoforge-1.21.1:1.0.0")

    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
}

publishMods.platforms.configureEach {
    requires 'kotlin-for-forge', 'curios', 'geckolib', 'biolith', 'lithostitched', 'hybrid-api'
}
