name: Build and Package Java Project with Gradle

on:
  push:
    branches:
      - '**'  # Executa em qualquer branch
  pull_request:
    branches:
      - '**'  # Também executa para todos os pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-java-app
        path: build/libs/*.jar
